### ISSUE TITLE
Error while reading ukwac jbt data

### ISSUE THREAD

**Issue by tezer** [tudarmstadt-lt/sensegram#11]
`sv = sensegram.SenseGram.load_word2vec_format('/home/myHome/Data/word2vec/sensegram/ukwac.senses.jbt', binary=True)`

gives error:
```
Traceback (most recent call last):
  File "/home/myHome/PycharmProjects/sensegram/my_progs/prog1.py", line 2, in <module>
    sv = sensegram.SenseGram.load_word2vec_format('/home/myHome/Data/word2vec/sensegram/ukwac.senses.jbt', binary=True)
  File "/home/myHome/PycharmProjects/sensegram/sensegram.py", line 45, in load_word2vec_format
    mod = word2vec.Word2Vec.load_word2vec_format(fname, fvocab, binary, encoding, unicode_errors)
  File "/home/myHome/virtualenv/sensegram/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1213, in load_word2vec_format
    add_word(word, weights)
  File "/home/myHome/virtualenv/sensegram/local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1195, in add_word
    result.wv.syn0[word_id] = weights
ValueError: could not broadcast input array from shape (69) into shape (100)
```
wiki data loaded without any problem

**Comment by tezer** [comment]
Sorry, the problem was on my side: data corruption while downloading
